name: Build & Push Docker Images to Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'data/**'

jobs:

  build-frontend:
    if: contains(github.event.head_commit.message, '[skip front]') == false
    runs-on: ubuntu-latest
    # Solo corre si hubo cambios en frontend/
    steps:
      - name: Check changed files
        id: changes
        uses: trilom/file-changes-action@v1.2.4
        
      - name: Skip job if no frontend changes
        if: steps.changes.outputs.files !~ 'frontend/'
        run: echo "No frontend changes → skipping job" && exit 0

      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Frontend Image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          build-args: |
            VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}
            VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}
          tags: |
            juanqu/suria-frontend:latest
            juanqu/suria-frontend:${{ github.sha }}

  build-data:
    runs-on: ubuntu-latest
    # Solo corre si hubo cambios en data/
    steps:
      - name: Check changed files
        id: changes
        uses: trilom/file-changes-action@v1.2.4
        
      - name: Skip job if no data changes
        if: steps.changes.outputs.files !~ 'data/'
        run: echo "No data changes → skipping job" && exit 0

      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Data ETL Image
        uses: docker/build-push-action@v6
        with:
          context: ./data
          file: ./dat/aDockerfile
          push: true
          tags: |
            juanqu/suria-data-etl:latest
            juanqu/suria-data-etl:${{ github.sha }}
