name: Build & Push Docker Images to Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'data/**'

jobs:

  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Get changed files
        id: changes
        uses: tj-actions/changed-files@v45

      - name: Skip if frontend folder not modified
        if: steps.changes.outputs.modified_files !contains('frontend/')
        run: echo "No frontend changes → skipping job" && exit 0

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Frontend Image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          build-args: |
            VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}
            VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}
          tags: |
            juanqu/suria-frontend:latest
            juanqu/suria-frontend:${{ github.sha }}

  build-data:
    runs-on: ubuntu-latest

    steps:
      - name: Get changed files
        id: changes
        uses: tj-actions/changed-files@v45

      - name: Skip if data folder not modified
        if: steps.changes.outputs.modified_files !contains('data/')
        run: echo "No data changes → skipping job" && exit 0

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Data ETL Image
        uses: docker/build-push-action@v6
        with:
          context: ./data
          file: ./data/Dockerfile
          push: true
          tags: |
            juanqu/suria-data-etl:latest
            juanqu/suria-data-etl:${{ github.sha }}
