name: Build & Push Docker Images to Docker Hub

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - 'data/**'

jobs:

  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get changed files
        id: changes
        uses: tj-actions/changed-files@v45

      - name: Detect frontend changes
        id: detect_frontend
        run: |
          echo "FILES_CHANGED=${{ steps.changes.outputs.all_modified_files }}" 
          if echo "${{ steps.changes.outputs.all_modified_files }}" | grep -q "^frontend/"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Stop job if frontend did not change
        if: steps.detect_frontend.outputs.changed == 'false'
        run: echo "No frontend changes → skipping job" && exit 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Frontend Image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          build-args: |
            VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}
            VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}
          tags: |
            juanqu/suria-frontend:latest
            juanqu/suria-frontend:${{ github.sha }}


  build-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get changed files
        id: changes
        uses: tj-actions/changed-files@v45

      - name: Detect data folder changes
        id: detect_data
        run: |
          echo "FILES_CHANGED=${{ steps.changes.outputs.all_modified_files }}" 
          if echo "${{ steps.changes.outputs.all_modified_files }}" | grep -q "^data/"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Stop job if data did not change
        if: steps.detect_data.outputs.changed == 'false'
        run: echo "No data changes → skipping job" && exit 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Data ETL Image
        uses: docker/build-push-action@v6
        with:
          context: ./data
          file: ./data/Dockerfile
          push: true
          tags: |
            juanqu/suria-data-etl:latest
            juanqu/suria-data-etl:${{ github.sha }}
